# Generated by Django 2.2.3 on 2019-07-29 17:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import purchases.formatChecker
import purchases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
                ('fullname', models.CharField(max_length=255, verbose_name='Full name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Legal address')),
                ('requisites', models.CharField(blank=True, max_length=255, verbose_name='Requisites')),
                ('bank_requisites', models.CharField(blank=True, max_length=255, verbose_name='Bank details')),
                ('chief', models.CharField(blank=True, max_length=45, verbose_name='Chief')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='Phone')),
                ('tax_system', models.CharField(choices=[('wvat', 'With VAT'), ('wovat', 'Without VAT')], default='wvat', max_length=5, verbose_name='Tax system')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Amount')),
                ('units', models.CharField(default='pcs.', max_length=16, verbose_name='Units')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Unit price')),
                ('attribute_values', models.ManyToManyField(blank=True, to='catalogue.AttributeValue', verbose_name='Attributes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Product', verbose_name='Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sa', 'Sale'), ('pu', 'Purchase')], default='sa', max_length=2, verbose_name='Purchase type')),
                ('status', models.CharField(choices=[('IB', 'Products in  basket'), ('NO', 'New order'), ('CN', 'Order canceled'), ('CF', 'Order confirmed'), ('ST', 'Order sent'), ('RC', 'Order received'), ('RT', 'Order returned')], default='IB', max_length=2, verbose_name='Deal type')),
                ('pay_status', models.CharField(choices=[('NP', 'Не оплачений'), ('AP', 'Оплачений аванс'), ('PU', 'Оплачений')], default='NP', max_length=2, verbose_name='Статус оплати')),
                ('invoice_number', models.CharField(max_length=45, verbose_name='Invoice number')),
                ('invoice_date', models.DateField(default=datetime.date.today, verbose_name='Invoice date')),
                ('in_stock', models.BooleanField(default=False, verbose_name='Available in stock')),
                ('arrival_date', models.DateField(default=datetime.date.today, verbose_name='Arrival date')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Value')),
                ('upload', purchases.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=purchases.models.docs_directory_path, verbose_name='Electronic copy')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.Company', verbose_name='Company')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Partner', verbose_name='Partner')),
                ('products', models.ManyToManyField(blank=True, related_name='products', through='purchases.InvoiceLine', to='catalogue.Product', verbose_name='Goods')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-date_created', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('PD', 'Pay on delivery'), ('BP', 'Bank payment'), ('BC', 'Bank card')], default='BP', max_length=2, verbose_name='Payment type')),
                ('payment_date', models.DateField(default=datetime.date.today, verbose_name='Payment date')),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Value')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.Purchase', verbose_name='Purchase'),
        ),
    ]
