# Generated by Django 2.2.3 on 2019-07-21 12:51

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
                ('fullname', models.CharField(max_length=255, verbose_name='Full name')),
                ('legal_address', models.CharField(blank=True, max_length=255, verbose_name='Legal address')),
                ('requisites', models.CharField(blank=True, max_length=255, verbose_name='Requisites')),
                ('bank_requisites', models.CharField(blank=True, max_length=255, verbose_name='Bank details')),
                ('chief', models.CharField(blank=True, max_length=45, verbose_name='Chief')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='Phone')),
                ('tax_system', models.CharField(choices=[('wvat', 'With VAT'), ('wovat', 'Without VAT')], default='wvat', max_length=5, verbose_name='Tax system')),
                ('avatar', models.ImageField(default='avatars/no_image.jpg', upload_to=accounts.models.avatar_directory_path, verbose_name='Фото')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День народження')),
                ('theme', models.CharField(choices=[('bl', 'Black'), ('wh', 'White')], default='bl', max_length=2, verbose_name='Theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=50, verbose_name='Посада')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='Телефон')),
                ('avatar', models.ImageField(default='avatars/no_image.jpg', upload_to=accounts.models.avatar_directory_path, verbose_name='Фото')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День народження')),
                ('theme', models.CharField(choices=[('bl', 'Black'), ('wh', 'White')], default='bl', max_length=2, verbose_name='Theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=45, verbose_name='City')),
                ('delivery_company', models.CharField(choices=[('NP', 'NEW POST')], default='NP', max_length=2, verbose_name='Delivery company')),
                ('delivery_method', models.CharField(choices=[('OD', 'Delivery to post office'), ('AD', 'Address delivery')], default='OD', max_length=2, verbose_name='Delivery method')),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('post_office', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Post office number')),
                ('main', models.BooleanField(default=False, verbose_name='Main address')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
            },
        ),
    ]
