# Generated by Django 2.2.3 on 2019-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190729_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerecord',
            name='from_date',
            field=models.DateField(verbose_name='Actual from'),
        ),
    ]
